# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m -Dmaven.test.skip=true'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'Java11'
    jdkArchitectureOption: 'x64'
    goals: 'package'

- task: CopyFiles@2
  name: copyjars
  displayName: Copy built artifacts to staging directory
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/target/*.jar'
    flattenFolders: true
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'build'
    publishLocation: 'Container'